os: linux
arch: ppc64le
sudo: required

matrix:
  include:
  - env: 
    - sys=debian-stretch 
    - dir=docker-ce/components/packaging/deb 
  - env: 
    - sys=ubuntu-xenial 
    - dir=docker-ce/components/packaging/deb 
  - env: 
    - sys=ubuntu-bionic 
    - dir=docker-ce/components/packaging/deb 
  - env: 
    - sys=centos 
    - dir=docker-ce/components/packaging/rpm 

script:
  - bash build.sh